### ISSUE TITLE
WordPress Install Fails - Uncaught Error: Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by schizek** [swiftotter/den#112]
**Version of Den**
1.0.0-beta.11

**Operating System and Installation Method**
Mac OS 12.6 via Brew

**Describe the bug**
The following bug is thrown when trying to setup a vanilla WordPress install.

`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/wp-includes/wp-db.php:1785`

**To Reproduce**
1. `PROJECT_NAME=wordpress-test`
2. Run...
    ```
    mkdir -p ~/Sites/"${PROJECT_NAME}".test && cd ~/Sites/"${PROJECT_NAME}".test && \
    den env-init "${PROJECT_NAME}" wordpress && \
    den sign-certificate "${PROJECT_NAME}".test && \
    den env up && \
    den env exec php-fpm bash -c 'curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && sudo mv wp-cli.phar /usr/local/bin/wp' && \
    den env exec php-fpm bash -c 'wp core download --path=./ --locale=en_US' && \
    den env exec php-fpm bash -c 'wp config create --dbhost=db --dbname=wordpress --dbuser=wordpress --dbpass=wordpress' && \
    den env exec php-fpm bash -c "wp core install --url=https://app.${PROJECT_NAME}.test --title='WP Sample' --admin_user=sglaser --admin_password=Puppies9? --admin_email=steph@fetchdesigns.com"
    ```
3. The following error is thrown...
    ```
    Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/wp-includes/wp-db.php:1788
    Stack trace:
    #0 /var/www/html/wp-includes/wp-db.php(724): wpdb->db_connect()
    #1 /var/www/html/wp-includes/load.php(561): wpdb->__construct('wordpress', 'wordpress', 'wordpress', 'db')
    #2 /var/www/html/wp-settings.php(124): require_wp_db()
    #3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('/var/www/html/w...')
    #4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
    #5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
    #6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
    #8 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
    #9 /usr/local/bin/wp(4): inc in /var/www/html/wp-includes/wp-db.php on line 1788
    Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
   ```

**Expected behavior**
I expect it would setup WordPress without an error

**Additional context**
I [reported the same issue on the DrPaynne fork](https://github.com/drpayyne/warden-multi-arch/discussions/26#discussioncomment-3861089).  It works fine on the original Warden project

**Comment by bap14** [comment]
The MySQL connection was deprecated in PHP5, and removed in 7 in favor of mysqli and PDO. What version of PHP and Wordpress are you trying to use?

**Comment by schizek** [comment]
I'm installing the latest version of WordPress and using whatever version of PHP comes with running 'den env-init wordpress'. Sorry I'm not at my computer at the moment to verify. However, as I recall when I debugged earlier, mysqli was not available in the environment which is why it's trying the older mysql connection.

**Comment by bap14** [comment]
It should be defaulting to PHP 7.4 with node 12. I just pulled that image down and ran it and checked if MySQL was available. It looks like it is via the mysqlnd package with PDO; however, mysqli itself isn't available.

This should be a simple fix of enabling the mysqli extension in the Dockerfile for the base php-fpm image here: https://github.com/swiftotter/den/blob/0c1abc69995e06ba15f58361ca1cc538cf5ee75d/images/php-fpm/Dockerfile#L20

**Comment by bap14** [comment]
Created PR https://github.com/swiftotter/den/pull/114 which will enable the MySQLi extension.

**Comment by navarr** [comment]
@schizek We've added the mysqli extension.  Can you please re-test this scenario and let us know how it goes?
