### ISSUE TITLE
Update default for PHP images to 8.1

### ISSUE THREAD

**Issue by bap14** [swiftotter/den#113]
**Is your feature request related to a problem? Please describe.**
PHP 7.4 is nearing its end of life (Nov. 28, 2022).

**Describe the solution you'd like**
Update the default PHP to be used with Den to 8.1

**Describe alternatives you've considered**
There aren't really alternatives, this is just a standard lifecycle event.

**Additional context**
PHP Supported Versions: https://www.php.net/supported-versions.php

**Other Notes**
While this isn't a high priority, it's something that should be done some time in November. The PHP 7.4 images can still be built and maintained, but they shouldn't be the default moving into December.

We should also find a way to properly announce this.

**Comment by DavidLambauer** [comment]
Makes sense! Would make sense to update composer version and potentially other dependencies as well.
