### ISSUE TITLE
Add php 7.0 for Magento 2.1.* versions or older

### ISSUE THREAD

**Issue by StenHigh** [swiftotter/den#132]
Please add a php 7.0 image to create a php container for magento version 2.1.*.

**Comment by navarr** [comment]
PHP images in the 7.0 and 7.1 flavors will be available with the successful completion of this action: https://github.com/swiftotter/den/actions/runs/3337936652

**Comment by StenHigh** [comment]
> PHP images in the 7.0 and 7.1 flavors will be available with the successful completion of this action: https://github.com/swiftotter/den/actions/runs/3337936652
> 
> Please note, PHP images < 7.2 will use XDebug 2 and Composer 2.2 LTS (as opposed to Composer 2.3) out of necessity

Thank you, it's a good job. But I have a Notice: "Use of undefined constant MCRYPT_RIJNDAEL_256". We need to add the php-extension mcrypt for old Magento 2 version.
