### ISSUE TITLE
Allow switching of document search distributions through .env file

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#14]
Similar to swiftotter/den#13, we should make it possible to easily switch between ElasticSearch and OpenSearch using only the .env file.

**Comment by ihor-sviziev** [comment]
Great job!
Just for reference I would add https://github.com/swiftotter/den/commit/5184743f423d20574306a46efddf010f15a4e785 and https://github.com/swiftotter/den/commit/2d98cb4749cab0547008340f82b1b9871ef225a1
