### ISSUE TITLE
pwgen not installed in FPM image

### ISSUE THREAD

**Issue by jkenneydaniel** [swiftotter/den#154]
**Is your feature request related to a problem? Please describe.**
When following the M2 environment documentation - upon reaching the step to generate admin account, `pwgen` is not installed in the fpm container resulting in an error

`bash: pwgen: command not found`

https://github.com/swiftotter/den/blame/main/docs/environments/magento2.md#L175

**Describe the solution you'd like**
Install `pwgen` in the images for container.

**Comment by jkenneydaniel** [comment]
I wasn't sure which template this belonged under so I used feature request.

**Comment by navarr** [comment]
Live after the merge of #155
