### ISSUE TITLE
Unable to connect to MySQL 8.0.26 server from PHP Image Command Line

### ISSUE THREAD

**Issue by lbajsarowicz** [swiftotter/den#168]
**Version of Den**
```
$ den version
in-dev
```

**Image**
```
    image: ghcr.io/swiftotter/den-php-fpm-magento2:8.1-node14
```

**Describe the bug**
```
www-data@swm-php-fpm:/var/www/html$ mysql --host="tmp-mysql" --user="root" --password="magento" magento_integration_tests
ERROR 1045 (28000): Plugin sha256_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/sha256_password.so: No such file or directory

```

**To Reproduce**
1. Change MySQL image to `mysql-server:8.0.26`
  ```
version: "3.5"
services:
  tmp-mysql:
    image: mysql/mysql-server:8.0.26
  ```

**Expected behavior**
I am able to connect to MySQL server

**Screenshots**

**Additional context**
Solution:
```
 sudo apk add mariadb-connector-c
```

https://pkgs.alpinelinux.org/contents?branch=edge&name=mariadb-connector-c&arch=x86&repo=main
https://mariadb.com/kb/en/authentication-plugin-sha-256/#client-authentication-plugins

**Comment by navarr** [comment]
That's interesting. Does this error occur when connecting from PHP too, or only when using the MySQL client on the PHP image?

**Comment by lbajsarowicz** [comment]
@navarr Looks like the issue affects only CLI 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1639941/206405678-a15d9569-6a85-41fd-871a-76e898e81b9d.png">

**Comment by lbajsarowicz** [comment]
Good job @navarr
