### ISSUE TITLE
Den dashboard and CLI version show "in-dev" with version 1.0.0-beta.12

### ISSUE THREAD

**Issue by bap14** [swiftotter/den#170]
**Version of Homebrew**
Homebrew 3.6.14
Homebrew/homebrew-core (git revision eea21d49db8; last commit 2022-12-07)
Homebrew/homebrew-cask (git revision 28e739ceb4; last commit 2022-12-07)

**Operating System and Installation Method**
MacOS Ventura 13.0.1

**Describe the bug**
After upgrade to 1.0.0-beta.12, the version on the Den dashboard and CLI is "in-dev"

**To Reproduce**
1. Install or Upgrade Den via brew: `brew upgrade den`
2. Restart (or start) Den: `den svc up`
3. Visit Den dashboard: https://den.test/

**Expected behavior**
Den dashboard and CLI both show "in-dev" as the version

**Screenshots**

**Additional context**
Looks like the version file read by the dashboard was not updated with the tagged version number: https://github.com/swiftotter/den/blob/1.0.0-beta.12/version
Compare that to version 1.0.0-beta.11: https://github.com/swiftotter/den/blob/1.0.0-beta.11/version

**Comment by bap14** [comment]
<img width="448" alt="Screenshot 2022-12-07 at 10 27 37 AM" src="https://user-images.githubusercontent.com/15036826/206220840-0642f71c-b2c7-4efd-b1a9-440227087daf.png">
<img width="310" alt="Screenshot 2022-12-07 at 10 27 29 AM" src="https://user-images.githubusercontent.com/15036826/206220844-4b911a91-5fc4-4022-a3e8-5df52f9e7df5.png">

**Comment by navarr** [comment]
Fixed in 1.0.0-beta.13
