### ISSUE TITLE
PHP Build Matrix Unreliable

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#20]
Jobs in the PHP Build Matrix often fail with errors like:

*buildx failed with: ERROR: failed to solve: failed commit on ref "index-sha256:ef94a52de35da42cbe0137bdfad2cd894ce5b843f5ddc95bd1bbd4a058fbdf99": cannot reuse body, request must be retried
* buildx failed with: ERROR: failed to solve: failed commit on ref "manifest-sha256:350ca2269385d77bdae7762f7b8e80bcc6a9c82d093b27395ffca477c1e1517e": cannot reuse body, request must be retried
* buildx failed with: ERROR: failed to solve: failed commit on ref "layer-sha256:5841d8ced19d625dc381215cb1a3fd111341333a2c41b3a3d4e3def657310374": cannot reuse body, request must be retried
* buildx failed with: ERROR: failed to solve: unexpected status: 429 Too Many Requests
* buildx failed with: ERROR: failed to solve: failed to copy: cannot reuse body, request must be retried

Such errors should trigger a retry of the build command

**Comment by ihor-sviziev** [comment]
Looks like the issue is gone. Probably that was some issue on Github side

**Comment by navarr** [comment]
For the nightlies, kind of.  Whenever I push an update to the PHP images though I have to re-run failed builds a few times.  The nightlies, if nothing has changed, they just use the cache and so there's nothing to update now

**Comment by navarr** [comment]
Example, last night's daily: https://github.com/swiftotter/den/actions/runs/2969274055/attempts/1

**Comment by bap14** [comment]
Some Relevant Issues
- docker/build-push-action#626
- docker/build-push-action#452

In issue docker/build-push-action#626 it says they released an update on June 3 to potentially fix this; however, all the references seem to not be using the matrix.

One option that was suggested in docker/build-push-action#452 was to add labels to the image. Some say it works, some say it doesn't.

It would lengthen the overall build process, but you could set the [`max-parallel`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) value on the matrix to be `1` so it only executes one build at a time, see if that runs more reliably.

**Comment by navarr** [comment]
@bap14 I did see! (Blackfire isn't yet available for 8.2)  I'm going to try raising parallelization a little at a time to see where we might be able to get it, since 3 hours for image builds that are 2-5 minutes each is a bit long.

I think we were essentially just hitting rate limits before, and the code doesn't have any ability to backoff, which is frustrating.
