### ISSUE TITLE
When moving from Warden, tunnel does not work

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#28]
Workaround:

* `sudo nano /etc/ssh/ssh_config`
* Change IdentityFile for tunnel.warden.test to `~/.den/tunnel/ssh_key`

**Comment by ihor-sviziev** [comment]
I believe the domain should be `tunnel.den.test`, so that there wouldn't be any conflicts

**Comment by ihor-sviziev** [comment]
Also, having a similar issue with SSL certificates - they're not trusted.
The main reason - we're re-using warden path for proxy SSL cert 
https://github.com/swiftotter/den/blob/7672c5e7fb3843d2904c1e4a5d00e6320c75ab83/commands/install.cmd#L28-L52

**Comment by navarr** [comment]
I've so far been erring on the side of keeping WARDEN_ and warden.test to reduce complexity during a switch.

Ideally, it's a drop-in replacement.  Tunnel would work after install, etc. etc.
