### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#29]
It's used in:
- https://github.com/swiftotter/den/blob/0a7ac1ec6e22329387e996d2a7044aac3609f21e/commands/usage.help#L4-L10
- https://github.com/swiftotter/den/blob/0a7ac1ec6e22329387e996d2a7044aac3609f21e/homepage/src/html/index.html#L6-L12

Warden used the following font to generate a logo:
https://patorjk.com/software/taag/#p=display&f=Slant&t=Warden
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1873745/187185090-b19a18bc-75db-4c97-b9e6-d041e3b40c34.png">

We can just use another name - Den:
https://patorjk.com/software/taag/#p=display&f=Slant&t=Den
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1873745/187185122-81863ad8-a221-42cb-b021-02aec87391a1.png">

or den
https://patorjk.com/software/taag/#p=display&f=Slant&t=den
<img width="193" alt="image" src="https://user-images.githubusercontent.com/1873745/187185260-2fe086a4-1faf-44d7-87f1-35413f65777d.png">

My suggestion for homepage:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/1873745/187186513-c3f13696-885a-45c7-b088-ec47f0a64d3e.png">

```html
<header class="align--center pt3">
        <div class="container--lg border--bottom pb3">
            <pre class="warden-mark">    ____           
   / __ \___  ____ 
  / / / / _ \/ __ \
 / /_/ /  __/ / / /
/_____/\___/_/ /_/ </pre>
            <p class="pt1">Fork of <a class="link" href="https://warden.dev/" target="_blank">Warden</a></p>
        </div>
    </header>
```

**Comment by ihor-sviziev** [comment]
Also `den` command shows incorrect version:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1873745/187187878-9e216cd1-ecc6-40b9-a12d-d7508fcf1a8e.png">

**Comment by ihor-sviziev** [comment]
@navarr,
do you agree to use the logo like this (including the phrase fork of Warden)?
<img width="306" alt="image" src="https://user-images.githubusercontent.com/1873745/187186513-c3f13696-885a-45c7-b088-ec47f0a64d3e.png">

**Comment by navarr** [comment]
@ihor-sviziev Yeah!
