### ISSUE TITLE
Determine replacement PHP image for RPM (ARM Required)

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#3]
Must support:
* amd64
* arm64/aarch64
* XDebug 3
* Blackfire

**Comment by navarr** [comment]
I'd like to make this image leaner, if possible.  It's a fairly large matrix.  For each version (7.4, 8.0, 8.1, 8.2) we need:

* PHP-FPM
* PHP-FPM + XDebug 2 (where applicable)
* PHP-FPM + XDebug 3 (where applicable)
* PHP-FPM + Blackfire

And then we need each of those for Magento 1, and Magento 2.

That's somewhere around 32 builds (dropping support for 7.2 and 7.3 - the last builds for those can be "final" unless needed)

**Comment by navarr** [comment]
Work on this is being done on the `alpine-php` branch - slowly

**Comment by navarr** [comment]
@ihor-sviziev Looks like when he did it it was to avoid issues with Source Guardian.  Den will not including any code obfuscation loaders in the base images, so hopefully it will not be a concern.

My current plan is to move forward with alpine and then only move off if there's an issue we can't resolve on it.

**Comment by kingletas** [comment]
I think there were also some issues with Magento/Composer Patching too but I could be wrong or remembering it wrong @navarr. 

I do like the idea of using Alpine too. I use it locally for most of my containers.

**Comment by ihor-sviziev** [comment]
@navarr i would drop xdebug 2 support in favor to xdebug 3

**Comment by mautz-et-tong** [comment]
OpenMage is providing a php-fpm container that supports Apple Silicon: https://github.com/OpenMage/docker-php with xdebug3 and some other stuff. Maybe you want to take a closer look. I could easily make this compatible to warden.

**Comment by ihor-sviziev** [comment]
FYI here is good example of Ubuntu-based images, that looks quite similar to original warden https://github.com/serversideup/docker-php

**Comment by mautz-et-tong** [comment]
As mentioned [here](https://github.com/swiftotter/den/discussions/5) I would make the effort to optimize the OpenMage Images for warden including issues discussed in this project if there is any interest.

**Comment by navarr** [comment]
@mautz-et-tong I appreciate the offer but we're very close with our own PHP images
