### ISSUE TITLE
When moving from Warden, ssl certificates are not trusted

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#31]
The main reason - is we're re-using the warden path for proxy SSL cert
https://github.com/swiftotter/den/blob/7672c5e7fb3843d2904c1e4a5d00e6320c75ab83/commands/install.cmd#L28-L52

**Comment by navarr** [comment]
After the changes in #19 to make the Den directory `~/.den` this should've been fixed on a subsequent `den install`.

Are you not experiencing that?

**Comment by ihor-sviziev** [comment]
@navarr see #32
