### ISSUE TITLE
Php-fpm images - sudo su -l shows errors

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#41]
```
:/var/www/html$ sudo su -l
-ash: /etc/profile.d/bind.sh: line 3: bind: not found
-ash: /etc/profile.d/bind.sh: line 4: bind: not found
ash: 0: unknown operand
ash: 0: unknown operand
root@talisa-php-fpm:~#

```

**Comment by ihor-sviziev** [comment]
Looks like that behavior caused by these files 
https://github.com/swiftotter/den/tree/main/images/php-fpm/context/etc/profile.d

**Comment by navarr** [comment]
That does tackle the bind.sh errors, but I'm still having issues finding the two unknown operand issues

**Comment by navarr** [comment]
Yup.  Just have to figure out how to make these files run using bash instead of ash.  `#!/bin/bash` as Line 1 doesn't fix it
