### ISSUE TITLE
Varnish 6.2, 6.3, 6.4 fail to start on ARM64

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#60]
After moving to alpine-based varnish images, varnish 6.5 stopped working
```
$ den env ps
NAME                     COMMAND                  SERVICE             STATUS              PORTS
myproj-db-1              "docker-entrypoint.s…"   db                  running             3306/tcp, 33060/tcp
myproj-elasticsearch-1   "/tini -- /usr/local…"   elasticsearch       running             9200/tcp, 9300/tcp
myproj-nginx-1           "/docker-entrypoint.…"   nginx               running             80/tcp
myproj-php-debug-1       "docker-entrypoint p…"   php-debug           running             9000/tcp
myproj-php-fpm-1         "docker-entrypoint p…"   php-fpm             running             9000/tcp
myproj-redis-1           "docker-entrypoint.s…"   redis               running             6379/tcp
myproj-varnish-1         "docker-varnish-entr…"   varnish             exited (127)
```

```
$ den env logs varnish
Error: Cannot create working directory '/var/lib/varnish/<project>-varnish/': Permission denied
(-? gives usage)
```

## Broken Images
- [x] 6.0
- [ ] 6.2
- [ ] 6.3
- [ ] 6.4
- [x] 6.5

**Comment by navarr** [comment]
Varnish 6.5 is a "Legacy" image. It's an AMD64 image as opposed to a ARM image. If it's missing envsubst then it doesn't have gettext installed and that's something I should be able to fix

**Comment by ihor-sviziev** [comment]
@navarr, I think it's better to switch back to centos stream based images as we had before https://github.com/swiftotter/den/commit/5e1bc364f6ff7b47f4cf4d3c29e99a63f3fb963c

**Comment by navarr** [comment]
Varnish 6.0 now works on ARM64.  6.2-6.5 do not.  I cannot confirm if they do or do not work on AMD64 at this time.

**Comment by navarr** [comment]
6.2, 6.3, and 6.4 cannot be installed the same way as 6.5 using the CentOS Stream and Packagecloud repo.

**Comment by ihor-sviziev** [comment]
@navarr, I think for varnish 6.2, 6.3, 6.4 we might build the only amd64 images

**Comment by navarr** [comment]
Since Warden only supported 6.4 (out of 6.2-6.4), and these images are much harder to setup - I'm going ahead and dropping support.  I think 6.0 and 6.5 will likely be good enough.

**Comment by ihor-sviziev** [comment]
Great! Thank you so much!
