### ISSUE TITLE
Den Dashboard can show out-of-date version

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#72]
After upgrading Den, the dashboard can show a version that is out of date.

**Comment by bap14** [comment]
@navarr There are a couple ways this can be solved:

# The HTML file is mounted via `docker-compose.yml`
#- This is probably the fastest but means that either a template is used and the real file is generated for each release, or needs to be updated during the "version update" commit
# Somehow the docker image is tagged / labeled with the version it was built with, and during `den svc up` it's checked and the image is rebuilt if necessary
#- This is the most complicated and means the user should always see the latest dashboard, potentially without a way to easily revert
# The version string is converted to a server-side include and pulls in the value of the already existing `version` file
#- This is relatively easy to convert to and brings in the version file as a mount; however, it assumes that the dashboard will generally never have work done no it

I'd lean towards the first option as being the easiest, and most flexible in the future, even if it is a little extra work during release.

**Comment by navarr** [comment]
> @navarr There are a couple ways this can be solved:
> 
> 1. The HTML file is mounted via `docker-compose.yml`
>     - This is probably the fastest but means that either a template is used and the real file is generated for each release, or needs to be updated during the "version update" commit
> 1. Somehow the docker image is tagged / labeled with the version it was built with, and during `den svc up` it's checked and the image is rebuilt if necessary
>     - This is the most complicated and means the user should always see the latest dashboard, potentially without a way to easily revert
> 1. The version string is converted to a server-side include and pulls in the value of the already existing `version` file
>     - This is relatively easy to convert to and brings in the version file as a mount; however, it assumes that the dashboard will generally never have work done no it
> 
> I'd lean towards the first option as being the easiest, and most flexible in the future, even if it is a little extra work during release.

I actually tried mounting first. Default Mac mount privileges though preclude wardens directory. The way this is avoided with SSL certificates and such is that they are generated once and stored in `~/.warden`

It may be possible to do this with a brew instruction of some sort that replaces the file every upgrade.

We are currently using performing option 2, but services do not automatically rebuild on upgrade

**Comment by bap14** [comment]
@navarr Could also add a check to the `svc` command that checks `~/.warden/version` against `<WARDEN_PATH>/version` and if they're different copies it over. I'm not familiar with brew and how it operates, but this seems like a more self-contained solution in case of manual installation.

Just trying to offer an alternative that moves this forward to a good solution.
