### ISSUE TITLE
Composer symlink fails for Composer v1 Projects

### ISSUE THREAD

**Issue by jkenneydaniel** [swiftotter/den#74]
When creating a project which requires Composer v1 - the entrypoint doesn't symlink Composer v1 as it's missing a block to do so.

https://github.com/swiftotter/den/blob/main/images/php-fpm/context/docker-entrypoint#L33

No equivalent block exists for Composer 1
```
# Configure composer2 as default when specified
if [[ "${COMPOSER_VERSION:-}" == "2" ]]; then
  sudo cp /usr/bin/composer2 /usr/bin/composer
fi
```

**Comment by navarr** [comment]
Updated image will be available when run has completed successfully: https://github.com/swiftotter/den/actions/runs/3105564492
