### ISSUE TITLE
Den install does nothing when switching from Warden

### ISSUE THREAD

**Issue by jkenneydaniel** [swiftotter/den#76]
My setup:

I had Warden installed, without removing it, I ran `warden svc down`.
Installed den via Brew on OSX, and attempted to run `den install`.

What happened:
Nothing happened.

Expected result:

Den update SSH config for Den SSH tunnel (similar to Warden tunnel)
Den should setup trust for Den SSL root certificate

Notes:

When removing the original Warden entry to `/etc/ssh/ssh_config` and re-running `den install`, it successfully placed the Den SSH config for tunnel.den.test so it appears that the mechanism that drives install for Den is still looking to confirm if the Warden tunnel config exists and not Den.

Edit: Confirmed, that is indeed what's happening:
https://github.com/swiftotter/den/blob/main/utils/install.sh#L5

**Comment by jkenneydaniel** [comment]
Also - this may be important - it appears that something _does_ indeed happen with `den install` and the SSL certs. However, the `svc` containers (I believe) need to be restarted so the networks can be recreated for the certs to be trusted as expected.

This may require more testing.

**Comment by navarr** [comment]
We do modify the certs:

```bash
  # Migrate from Warden to Den
  if grep "~/.warden/tunnel/ssh_key" /etc/ssh/ssh_config >/dev/null; then
      sudo sed -i.bak 's/~\/.warden/~\/.den/' /etc/ssh/ssh_config
  fi
```

https://github.com/swiftotter/den/blob/main/utils/install.sh#L26

Though I see we're not outputting any sort of message when we do that.

Are you experiencing issues with your Den root SSL not being trusted?

**Comment by navarr** [comment]
We've had several new installers and issue creators on the repo recently, and I haven't seen anyone follow this up with shared experiences, so I'm closing it until such time comes :)
