### ISSUE TITLE
Magerun cannot be ran

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#79]
**Version of Den**
in-dev

**Image**
den-php-fpm-magento2:8.1-node16

**Describe the bug**
n98-magerun2's binary is owned by root and cannot be executed by the www-data user

**To Reproduce**
1. `den env up;den shell`
2. `n98-magerun2 list`

**Expected behavior**
List of Magerun commands is displayed

**Actual behavior**
Could not open input file: /usr/local/bin/n98-magerun2

**Comment by bap14** [comment]
@navarr The fact it's owned by root isn't the issue, as the composer binaries are owned by root as well. The issue is that n98-magerun2 isn't readable by anyone except root:
```
www-data@mcico-php-fpm:/var/www/html$ ls -la /usr/local/bin/n98-magerun2
-rwx--x--x    1 root     root       5498190 Aug  5 13:49 /usr/local/bin/n98-magerun2

www-data@mcico-php-fpm:/var/www/html$ ls -la /usr/bin/composer2
-rwxr-xr-x    1 root     root       2799637 Aug 22 18:39 /usr/bin/composer2
```

PR incoming.

**Comment by bap14** [comment]
PR 80 resolves this. https://github.com/swiftotter/den/pull/80
