### ISSUE TITLE
Allow customization of blackfire-based images

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#8]
* Add `WARDEN_ENV_PATH` to the list of search paths `appendEnvPartialIfExists` uses.

Source: https://github.com/davidalger/warden/issues/285

**Comment by ihor-sviziev** [comment]
@navarr, what about porting https://github.com/davidalger/warden/pull/451 ?

**Comment by navarr** [comment]
Thanks Ihor!  I'll definitely review that PR and consider merging
