### ISSUE TITLE
Implement ability to configure (and persist) dnsmasq configuration for alternate TLDs

### ISSUE THREAD

**Issue by dzschille** [swiftotter/den#86]
In Warden configuring a custom TLD can be accomplished by adding the following to ~/.warden/.env to inject additional configuration into the dnsmasq container via standard docker-compose .env file processing:

```
WARDEN_DNSMASQ_CONF_ADDITIONAL="address=/.local/127.0.0.1"
```
or
```
WARDEN_DNSMASQ_CONF_ADDITIONAL="address=/.local/127.0.0.1\naddress=/.dev/127.0.0.1"
```
This implementation also allows for easily overriding the use of CloudFlare DNS by setting custom values on WARDEN_DNSMASQ_NS1 and WARDEN_DNSMASQ_NS2.

After changing settings in the env file, simply run warden svc up to recreate dnsmasq with the new configuration.

Do you will support alternate TLDs also?
See [original ticket](https://github.com/davidalger/warden/issues/214) from Warden.

**Comment by navarr** [comment]
`WARDEN_DNSMASQ_CONF_ADDITIONAL` is supported by Den.  Instead of `~/.warden/.env` the new location would be `~/.den/.env`

**Comment by navarr** [comment]
The variable is loaded into the docker-compose here: https://github.com/swiftotter/den/blob/main/docker/docker-compose.yml#L53

It works exactly the same as in Warden.
